import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'zh' | 'en'
type Dictionary = Record<string, string>

const english: Dictionary = {
  '西湖无碍行': 'West Lake For All', '地图': 'Map', '路线': 'Routes', '设施': 'Facilities', '帮助': 'Help', '设置': 'Settings',
  '从西湖开始，自在出发': 'Start at West Lake, travel with ease', '每一种抵达，': 'Every way of arriving', '都值得被照顾。': 'deserves thoughtful care.',
  '把语音导览、无障碍设施和友好路线放进一张地图，让每个人都能从容游西湖。': 'Voice guides, accessible facilities and considerate routes on one map—so everyone can enjoy West Lake with confidence.',
  '类友好服务': 'service modes', '处示例设施': 'sample facilities', '条示范路线': 'sample routes', '我需要哪些帮助？': 'What support do I need?', '可多选，地图内容会随之调整。': 'Choose any that apply. The map will adapt.',
  '现在，从这里出发': 'Start from here', '查找景点、路线与身边的无障碍设施': 'Find attractions, routes and nearby accessible facilities', '搜索景点或服务…': 'Search attractions or services…', '我的位置': 'My location',
  '景点': 'Attraction', '无障碍设施': 'Accessible facility', '演示地图': 'Demo map', '推荐地点': 'Recommended places', '个结果': 'results', '没有找到匹配地点，请换个关键词。': 'No matching places. Try another keyword.',
  '现场帮助': 'On-site support', '遇到障碍，不必独自解决。': 'You do not have to face barriers alone.', '呼叫志愿同行，或预约坡道和感官导览设备。当前为交互演示。': 'Call a volunteer companion or reserve a ramp and sensory guide device. This is an interactive demo.', '呼叫志愿者': 'Call a volunteer', '预约辅助设备': 'Reserve equipment',
  '今日推荐': 'Today’s pick', '少一点顾虑，': 'Fewer worries,', '多一点湖光。': 'more of the lake.', '路线信息为首版示例，请出行前结合现场情况确认。': 'Route details are samples. Confirm current conditions before travelling.', '查看全部友好路线': 'View all accessible routes', '示范路线': 'Sample route',
  '友好路线': 'Accessible routes', '更安心的西湖游线': 'Explore West Lake with confidence', '优先展示路面、坡度、台阶和休息设施。以下均为示范信息，出行前请向景区确认。': 'Surface, slope, steps and rest facilities come first. All details are samples—confirm with the site before visiting.', '全部': 'All', '路面': 'Surface', '坡度': 'Slope', '注意：': 'Notice: ',
  '景点无障碍指南': 'Attraction accessibility guide', '返回地图': 'Back to map', '本页为示例信息，开放情况和无障碍设施请以现场公告为准。': 'This page contains sample information. Follow on-site notices for opening and accessibility details.', '到访之前': 'Before your visit', '开放时间': 'Opening hours', '适合体验': 'Good for', '无障碍提示': 'Accessibility notes',
  '身边的帮助': 'Support nearby', '无障碍设施目录': 'Accessible facilities', '快速找到厕所、坡道、休息点与人工服务。设施状态不实时更新，请以现场为准。': 'Quickly find toilets, ramps, rest areas and staffed services. Availability is not real-time.', '设施类型': 'Facility type', '全部设施': 'All facilities', '从这里预约设备': 'Reserve equipment here',
  '按你的方式使用': 'Use it your way', '无障碍设置': 'Accessibility settings', '设置只保存在当前设备，不会上传，也不会收集个人健康信息。': 'Settings stay on this device. They are not uploaded and no health information is collected.', '大字号': 'Large text', '放大正文和主要控件文字': 'Enlarge body text and primary controls', '高对比模式': 'High contrast', '增强文字、边框与背景的对比': 'Increase contrast between text, borders and backgrounds', '减少动态效果': 'Reduce motion', '关闭非必要动画和过渡': 'Disable non-essential animation and transitions', '自动播报': 'Auto narration', '进入景点时自动准备语音导览': 'Prepare voice guidance when entering an attraction', '视觉提醒': 'Visual alerts', '用醒目的文字通知呈现重要信息': 'Show important information with prominent text notices', '语音速度': 'Speech rate', '当前': 'Current', '倍速': '× speed', '恢复默认设置': 'Restore defaults',
  '语音与文字导览': 'Voice and text guide', '播放导览': 'Play guide', '重新播放': 'Replay', '继续': 'Resume', '暂停': 'Pause', '停止': 'Stop', '从头': 'From start', '当前浏览器不支持语音朗读，您仍可阅读下方完整文字稿。': 'This browser does not support speech playback. The full transcript remains available below.',
  '视障友好': 'Vision support', '听障友好': 'Hearing support', '行动友好': 'Mobility support', '无障碍厕所': 'Accessible toilet', '坡道': 'Ramp', '电梯': 'Lift', '休息点': 'Rest area', '医疗点': 'Medical point', '无障碍停车': 'Accessible parking', '服务中心': 'Service centre',
  '安心同行 · 演示服务': 'Travel with confidence · Demo', '需要帮助，': 'Need a hand?', '我们一起想办法。': 'Let’s find a way together.', '现场呼叫或提前预约志愿同行，也可以请求辅助设备配送。当前功能不会真正发送请求。': 'Call now or book a volunteer companion, and request assistive equipment delivery. No real request will be sent.',
  '这里不是紧急呼叫渠道': 'This is not an emergency channel', '遇到人身安全或医疗紧急情况，请立即拨打 110 或 120。': 'For personal safety or medical emergencies, call 110 or 120 immediately.', '一对一全程协助': 'One-to-one support', '呼叫或预约志愿者': 'Call or book a volunteer', '视障引导、轮椅路线陪同、文字沟通与设备操作。': 'Sighted guidance, wheelchair route support, text communication and device assistance.', '开始预约': 'Start booking', '服务点配送': 'Service-point delivery', '简易便携坡道与多媒体感官导览装置。': 'Portable ramps and multimedia sensory guide devices.', '查看设备': 'View equipment', '无需说话也能表达': 'Communicate without speaking', '打开大字求助卡': 'Open large-text help card', '立即打开': 'Open now',
  '记录': 'Records', '我的演示服务': 'My demo services', '清除记录': 'Clear records', '还没有服务记录': 'No service records yet', '完成一次志愿者或设备预约后，可以在这里跟踪演示状态。': 'After booking a volunteer or device, track the demo status here.', '演示记录': 'Demo record', '志愿同行服务': 'Volunteer companion', '辅助设备': 'Assistive equipment', '当前状态：': 'Current status: ', '模拟匹配志愿者': 'Matched demo volunteer', '会面核验码：': 'Meeting verification: ', '模拟推进状态': 'Advance demo status', '取消请求': 'Cancel request',
  '已提交': 'Submitted', '匹配中': 'Matching', '已确认': 'Confirmed', '已会面': 'Met', '陪同中': 'Accompanying', '已完成': 'Completed', '已预约': 'Reserved', '准备中': 'Preparing', '配送中': 'Delivering', '待领取': 'Ready to collect', '使用中': 'In use', '已归还': 'Returned', '已取消': 'Cancelled',
  '志愿同行': 'Volunteer companion', '预约一位同行者': 'Book a companion', '返回帮助中心': 'Back to help centre', '第': 'Step', '步': 'of 2', '此为交互演示，不会向真实组织发送请求。': 'This is an interactive demo. No request is sent to a real organisation.', '你什么时候需要帮助？': 'When do you need help?', '现在需要': 'I need help now', '模拟现场快速匹配': 'Simulate rapid on-site matching', '提前预约': 'Book ahead', '选择未来日期与时段': 'Choose a future date and time', '会面地点': 'Meeting point', '预约日期与时间': 'Booking date and time', '预计陪同时长': 'Expected duration', '需要哪些帮助？': 'What support do you need?', '可多选': 'Select all that apply', '沟通方式': 'Communication method', '补充说明（选填）': 'Additional notes (optional)', '例如：使用手动轮椅，希望避开拥挤路段': 'Example: I use a manual wheelchair and prefer quieter routes', '查看预约摘要': 'Review booking', '请填写会面地点、时间并至少选择一种帮助需求。': 'Add a meeting point and time, and choose at least one support need.', '请确认志愿同行需求': 'Confirm volunteer support', '服务时间': 'Service time', '预计时长': 'Duration', '帮助需求': 'Support needs', '提交演示请求': 'Submit demo request',
  '视障引导': 'Sighted guidance', '手语或文字沟通': 'Sign or text communication', '轮椅协助': 'Wheelchair assistance', '路线陪同': 'Route companionship', '设备操作': 'Device assistance', '其他帮助': 'Other support', '口头交流': 'Spoken communication', '文字交流': 'Text communication', '手语交流': 'Sign language', '简单清晰指令': 'Simple clear instructions', '1 小时': '1 hour', '2 小时': '2 hours', '半天': 'Half day', '全天': 'Full day',
  '预约配送或领取': 'Reserve delivery or collection', '选择辅助设备': 'Choose assistive equipment', '模拟库存': 'Demo stock', '件': 'units', '配送或领取服务点': 'Delivery or collection point', '暂无': 'Unavailable', '建议改选：': 'Suggested alternative: ', '使用日期与时间': 'Date and time of use', '数量': 'Quantity', '当前模拟库存': 'Current demo stock', '障碍位置': 'Barrier location', '例如：孤山路西泠桥东侧台阶': 'Example: steps east of Xiling Bridge on Gushan Road', '台阶数量': 'Number of steps', '需要哪些感官模式？': 'Which sensory modes do you need?', '归还点': 'Return point', '现场备注（选填）': 'On-site notes (optional)', '该服务点暂无此设备，请选择建议的其他服务点。': 'This device is unavailable here. Choose the suggested service point.', '请完成时间、位置和使用需求。': 'Complete the time, location and usage needs.', '请确认设备预约': 'Confirm equipment booking', '设备': 'Equipment', '服务点': 'Service point', '使用时间': 'Time of use', '体验模式': 'Experience modes', '现场评估': 'On-site assessment', '级台阶': 'steps', '提交演示预约': 'Submit demo booking',
  '听觉增强': 'Enhanced audio', '触觉节奏': 'Haptic rhythm', '视觉字幕': 'Visual captions', '向身边的人展示下面这句话': 'Show this message to someone nearby', '我需要引导，请告诉我前方的方向。': 'I need guidance. Please tell me what is ahead.', '请用文字和我交流，谢谢。': 'Please communicate with me in writing. Thank you.', '请帮我联系最近的无障碍服务点。': 'Please help me contact the nearest accessibility service point.', '这里有台阶，请协助我安全通过。': 'There are steps here. Please help me cross safely.', '选择求助内容': 'Choose a help message', '紧急情况请拨打 110 或 120': 'For emergencies, call 110 or 120', '关闭求助卡': 'Close help card', '提交前确认': 'Review before submitting', '提交后将生成模拟记录，你可以在帮助中心推进状态或取消。': 'A demo record will be created. You can advance or cancel it in the help centre.', '返回修改': 'Back to edit',
  '简易便携坡道': 'Portable access ramp', '由工作人员送达并评估现场后铺设，协助跨越短距离台阶。': 'Delivered and installed by staff after an on-site assessment for short flights of steps.', '工作人员铺设': 'Staff installation', '适配短台阶': 'Short-step access', '坡度、承重和台阶条件必须由工作人员确认，请勿自行铺设或使用。': 'Staff must confirm slope, load and step conditions. Do not install or use it yourself.', '多媒体感官导览装置': 'Multimedia sensory guide', '把西湖故事转换成声音增强、触觉节奏和高对比字幕。': 'Transforms West Lake stories into enhanced audio, haptic rhythm and high-contrast captions.', '设备为导览辅助，不替代助听器、导航杖或其他专业辅具。': 'This is a guide aid, not a replacement for hearing aids, mobility canes or professional assistive devices.',
  '中文': '中文', '英语': 'English', '切换到英语': 'Switch to English', 'Switch to Chinese': '切换到中文', '主要导航': 'Main navigation', '、': ', ', '桥': 'Bridge',
  '当前设备不支持定位，已使用西湖中心作为起点。': 'Location is not supported. West Lake centre is used as your start.', '正在请求定位授权…': 'Requesting location permission…', '已定位到您的当前位置。': 'Your current position has been located.', '未获得定位权限，已使用西湖中心；您仍可手动选择起点。': 'Location permission was not granted. West Lake centre is used; you can choose a start manually.', '搜索景点': 'Search attractions', '高德地图，显示西湖景点与无障碍设施': 'Amap showing West Lake attractions and accessible facilities', '西湖示意地图，显示景点与无障碍设施': 'West Lake demo map showing attractions and accessible facilities', '按需求筛选路线': 'Filter routes by need',
  '断桥残雪': 'Broken Bridge', '从北山街轻松抵达的湖岸视角': 'A lakeside view easily reached from Beishan Street', '断桥位于白堤东端，是西湖极具辨识度的景观入口。首版导览从平缓、开阔的北山街一侧开始。': 'Broken Bridge stands at the east end of Bai Causeway, one of West Lake’s most recognisable gateways. This guide starts from the broad, gentle Beishan Street side.', '全天开放': 'Open all day', '湖景': 'Lake view', '平缓路段': 'Gentle route', '语音导览': 'Voice guide', '北山街入口相对平缓': 'The Beishan Street entrance is relatively gentle', '桥面人流密集时建议结伴': 'Travel with a companion when the bridge is crowded', '沿线设有休息座椅': 'Rest seats are available along the route', '桥与湖的相遇': 'Where bridge meets lake', '2 分 40 秒': '2 min 40 sec', '你现在面向西湖，脚下是连接北山街与白堤的断桥。': 'You are facing West Lake, standing on Broken Bridge between Beishan Street and Bai Causeway.', '桥并没有真正断开。“断桥”之名与冬日残雪、远望桥面若隐若现的景象有关。': 'The bridge is not actually broken. Its name is associated with lingering winter snow that makes the bridge appear interrupted from afar.', '前方路面总体平缓。节假日人流较大，请沿右侧缓慢前行，并留意同行者提示。': 'The surface ahead is generally level. On busy holidays, keep right, move slowly and follow your companion’s guidance.',
  '曲院风荷': 'Quyuan Garden', '荷香、树荫与连续休息点': 'Lotus fragrance, shade and frequent rest points', '园区以荷花景观闻名，部分主游线较平整，树荫和休息空间丰富，适合放慢速度游览。': 'Known for its lotus scenery, the garden has level main paths, generous shade and many places to rest.', '园林': 'Garden', '轮椅友好': 'Wheelchair friendly', '主入口设缓坡': 'A gentle ramp is available at the main entrance', '部分支路为石板路': 'Some side paths use stone paving', '服务点附近有无障碍厕所': 'An accessible toilet is near the service point', '听见一池风荷': 'Hear the lotus in the wind', '3 分 10 秒': '3 min 10 sec', '这里是曲院风荷。夏季，风穿过大片荷叶，会形成连续而轻柔的摩擦声。': 'This is Quyuan Garden. In summer, wind moving through broad lotus leaves creates a continuous, gentle rustle.', '主游线两侧分布着水池与树木。靠近水边时，请留意低矮护栏。': 'Ponds and trees line both sides of the main route. Be aware of low railings near the water.', '前方约八十米有带靠背的休息座椅，右侧服务点附近设有无障碍厕所。': 'Backed seating is about 80 metres ahead, and an accessible toilet is near the service point on the right.',
  '雷峰塔景区': 'Leifeng Pagoda', '电梯辅助登高，俯瞰西湖南线': 'Lift-assisted access to views over southern West Lake', '雷峰塔提供电梯辅助游览，但入口、换乘与高峰期排队情况需要提前确认。': 'Leifeng Pagoda offers lift-assisted access. Confirm entrance, transfers and peak-time queues in advance.', '08:00–17:30（示例）': '08:00–17:30 (sample)', '文化': 'Culture', '字幕导览': 'Captioned guide', '入口区域有坡道': 'A ramp is available near the entrance', '塔内设电梯': 'A lift operates inside the pagoda', '高峰期建议联系工作人员': 'Contact staff during peak periods', '雷峰夕照': 'Sunset at Leifeng Pagoda', '2 分 20 秒': '2 min 20 sec', '雷峰塔位于西湖南岸的夕照山上，是西湖文化景观的重要地标。': 'Leifeng Pagoda stands on Xizhao Hill on the southern shore, an important landmark in West Lake’s cultural landscape.', '现塔为重建建筑，内部设有电梯。到达观景层后，可以从南向北俯瞰湖面。': 'The present pagoda is reconstructed and includes a lift. The observation level looks north across the lake.', '如需无障碍协助，请在入口服务台联系工作人员。': 'For accessibility assistance, contact staff at the entrance service desk.',
  '少年宫无障碍厕所': 'Youth Palace accessible toilet', '扶手': 'Grab rails', '低位洗手台': 'Low washbasin', '独立空间': 'Private room', '开放情况请以现场为准': 'Confirm opening on site', '断桥湖滨休息点': 'Broken Bridge lakeside rest point', '带靠背座椅': 'Backed seating', '树荫': 'Shade', '平整地面': 'Level surface', '节假日可能较拥挤': 'May be crowded on holidays', '曲院风荷游客服务中心': 'Quyuan Garden visitor centre', '人工协助': 'Staff assistance', '轮椅借用咨询': 'Wheelchair loan enquiries', '文字说明': 'Written information', '轮椅数量需现场确认': 'Wheelchair availability must be confirmed on site', '雷峰塔内部电梯': 'Leifeng Pagoda lift', '入口内': 'Inside entrance', '工作人员协助': 'Staff assistance', '可容纳轮椅': 'Wheelchair accessible', '运行情况请提前向景区确认': 'Confirm operation with the attraction in advance', '南山路医疗服务点': 'Nanshan Road medical point', '基础急救': 'Basic first aid', '示例位置，紧急情况请拨打 120': 'Sample location. Call 120 in an emergency', '北山街缓坡入口': 'Beishan Street gentle-ramp entrance', '连续缓坡': 'Continuous gentle ramp', '路面平整': 'Level surface', '雨天注意防滑': 'Surface may be slippery in rain', '湖滨无障碍停车位': 'Lakeside accessible parking', '邻近主路': 'Near the main road', '宽车位': 'Wide bay', '车位状态不实时更新': 'Parking availability is not real-time',
  '北山街—断桥轻松线': 'Beishan Street–Broken Bridge easy route', '少年宫': 'Youth Palace', '1.1 公里': '1.1 km', '约 24 分钟': 'About 24 min', '无台阶': 'Step-free', '2 处休息点': '2 rest points', '平整铺装为主': 'Mostly level paving', '缓坡，示例最大约 4%': 'Gentle slope, sample maximum about 4%', '从少年宫南门沿北山街向西': 'Head west along Beishan Street from the Youth Palace south gate', '420 米': '420 m', '右侧临近非机动车道': 'Cycle traffic is close on the right', '经过湖滨休息点，继续直行': 'Continue straight past the lakeside rest point', '360 米': '360 m', '从缓坡入口到达断桥东端': 'Use the gentle ramp to reach the east end of Broken Bridge', '320 米': '320 m', '高峰期人流密集': 'Crowded at peak times', '曲院风荷慢游环线': 'Quyuan Garden slow loop', '曲院风荷北门': 'Quyuan Garden north gate', '荷花池': 'Lotus pond', '1.6 公里': '1.6 km', '约 38 分钟': 'About 38 min', '树荫较多': 'Plenty of shade', '铺装路与少量石板路': 'Paved route with some stone paths', '整体平缓': 'Generally level', '由北门缓坡进入园区': 'Enter via the gentle ramp at the north gate', '280 米': '280 m', '在服务中心前向左转': 'Turn left before the service centre', '510 米': '510 m', '路口请留意观光车': 'Watch for sightseeing vehicles at the junction', '沿荷花池外侧游线前行': 'Follow the outer path around the lotus pond', '810 米': '810 m', '水边有低矮护栏': 'Low railings are present near the water',
  '湖滨无障碍服务点': 'Lakeside accessibility service point', '雷峰塔入口服务台': 'Leifeng Pagoda entrance desk', '北山街与杨公堤交会区域（示例）': 'Near Beishan Street and Yanggong Causeway (sample)', '湖滨步行街北段（示例）': 'North Lakeside pedestrian street (sample)', '南山路雷峰塔景区入口（示例）': 'Leifeng Pagoda entrance on Nanshan Road (sample)', '林老师': 'Volunteer Lin', '西湖暖行志愿服务队（演示）': 'West Lake Warm Journey Volunteers (demo)', '荷风 372': 'Lotus 372',
  '确认取消演示请求': 'Cancel demo request', '记录仍会保留。': 'The record will be retained.', '确认清除当前设备上的全部演示服务记录吗？': 'Clear all demo service records on this device?', '本机演示记录已清除': 'Local demo records cleared'
}

interface I18nValue { locale: Locale; setLocale(locale: Locale): void; t(text: string): string }
const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({children}:{children:ReactNode}) {
  const [locale,setLocaleState]=useState<Locale>(()=>localStorage.getItem('westlake-locale')==='en'?'en':'zh')
  useEffect(()=>{localStorage.setItem('westlake-locale',locale);document.documentElement.lang=locale==='zh'?'zh-CN':'en'},[locale])
  const value=useMemo<I18nValue>(()=>({locale,setLocale:(next)=>setLocaleState(next),t:(text)=>locale==='en'?(english[text]??text):text}),[locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n(){const value=useContext(I18nContext);if(!value)throw new Error('useI18n must be used inside I18nProvider');return value}
